export const CONDIMENTS_SECTIONS = [
  {
    id: "exotic-jams",
    label: "Exotic Jams",
    image: "/products/condiments/jams.png",
    imagePosition: "right",
    groups: [
      {
        title: null,
        items: [
          "Apple",
          "Plum",
          "Cherry",
          "Raspberry",
          "Strawberry",
          "Black Currant",
          "Red Currant",
          "Gooseberry",
          "Pear",
          "Apricot",
          "Peach",
          "Blueberry",
        ],
      },
    ],
  },
  {
    id: "spreads",
    label: "Spreads",
    image: "/products/condiments/spreads.png",
    imagePosition: "left",
    groups: [
      {
        title: null,
        items: [
          "Almond Butter",
          "Cashew Butter",
          "Peanut Butter",
          "Pecan Butter",
          "Sunflower Seed Butter",
          "Butter",
          "Cream Cheese",
          "Margarine",
          "Marmalade",
          "Avocado Spread",
          "Hummus",
          "Tahini",
          "Tapenade",
          "Chocolate Spread",
          "Honey",
        ],
      },
    ],
  },
  {
    id: "pickles-chutneys",
    label: "Pickles & Chutneys",
    image: "/products/condiments/pickles.png",
    imagePosition: "right",
    groups: [
      {
        title: "Pickles",
        items: [
          "Mango Pickle — Hot, Sweet or Mixed",
          "Lime Pickle — Hot or Mixed",
          "Mixed Pickle",
          "Chilli Pickle — Green or Red Chilli",
          "Garlic Pickle",
          "Ginger Pickle",
          "Tomato Pickle",
          "Aubergine (Brinjal) Pickle",
          "Gooseberry Pickle",
          "Carrot Pickle",
          "Gongura Pickle",
        ],
      },
      {
        title: "Chutneys",
        items: [
          "Tomato Chutney",
          "Mint (Pudina) Chutney",
          "Coconut Chutney",
          "Coriander Chutney",
          "Tamarind Date Chutney",
          "Garlic Chutney",
          "Onion Chutney",
          "Ginger Chutney",
          "Peanut (Groundnut) Chutney",
          "Ginger Garlic Paste",
        ],
      },
    ],
  },
  {
    id: "curry-pastes",
    label: "Curry Pastes",
    image: "/products/condiments/curry-paste.png",
    imagePosition: "left",
    groups: [
      {
        title: null,
        items: [
          "Tikka Masala Spice Paste",
          "Korma Spice Paste",
          "Rogan Josh Spice Paste",
          "Madras Spice Paste",
          "Vindaloo Spice Paste",
        ],
      },
    ],
  },
];