export const SPICES_SECTIONS = [
  {
    id: "whole-spices",
    label: "Whole Spices",
    image: "/products-page/spices/whole-spices.webp",
    imagePosition: "right",
    groups: [
      {
        title: null,
        items: [
          "Basil Seeds (Sabja)",
          "Bay Leaf (Tej Patta)",
          "Cardamom Pods Green (Choti Elaichi)",
          "Cardamom Pods Black (Badi Elaichi)",
          "Carom Seeds (Ajwain)",
          "Cloves (Laung)",
          "Cinnamon Sticks (Dalchini)",
          "Coconut Flakes (Nariyal Burada)",
          "Coriander Seeds Whole (Dhania)",
          "Cumin Seeds (Jeera)",
          "Dried Rose Petal (Gulab Pankhudiyan)",
          "Fennel Seeds (Saunf)",
          "Fenugreek Seeds (Methi)",
          "Fenugreek Leaves Dried (Methi)",
          "Mace Whole (Javitri)",
          "Mustard Seeds Black (Kaali Sarson)",
          "Mustard Seeds Yellow (Peeli Sarson)",
          "Nigella Seeds (Kalonji)",
          "Nutmeg Whole (Jaiphal)",
          "Poppy Seeds (Khus Khus)",
          "Star Anise (Chakra Phool)",
          "Saffron (Kesar)",
          "Red Chilli Whole (Lal Mirch)",
          "Red Chilli Flakes (Lal Mirch)",
          "White Pepper Whole (Safed Mirch)",
        ],
      },
    ],
  },
  {
    id: "ground-spices",
    label: "Ground Spices",
    image: "/products-page/spices/ground-spices.webp",
    imagePosition: "left",
    groups: [
      {
        title: null,
        items: [
          "Red Chilli Powder (Lal Mirch)",
          "Red Chilli Crushed (Kutti Lal Mirch)",
          "Kashmiri Red Chilli Powder (Kasmiri Mirch)",
          "Cumin Powder (Jeera)",
          "Cumin Coriander Powder (Jeera Dhania)",
          "Coriander Powder (Dhania)",
          "Coconut Desiccated (Nariyal Burada)",
          "Cinnamon Powder (Dalchini)",
          "Coarse Black Pepper (Kutti Kali Mirch)",
          "Cardamom Powder (Elaichi)",
          "Turmeric Powder (Haldi)",
          "Onion Powder",
          "Garlic Powder",
        ],
      },
    ],
  },
  {
    id: "blended-spices",
    label: "Blended Spices",
    image: "/products-page/spices/blended-spices.webp",
    imagePosition: "right",
    groups: [
      {
        title: null,
        items: [
          "Bihari Kebab Masala",
          "Butter Chicken Masala",
          "Chat Masala",
          "Chana Masala",
          "Chicken Masala",
          "Chettinad Masala",
          "Curry Masala",
          "Egg Curry Masala",
          "European Curry Masala",
          "Fish Masala",
          "Haleem Masala",
          "Hyderabadi Biryani Masala",
          "Karahi Masala",
          "Jal Jeera Masala",
          "Korma Masala",
          "Kolhapuri Masala",
          "Malvani Masala",
          "Meat Masala",
          "Mint Masala",
          "Madras Curry Masala",
          "Nihari Masala",
          "Paneer Masala",
          "Pani Puri Masala",
          "Pav Bhaji Masala",
          "Rajma Masala",
          "Pulao Masala",
          "Rasam Masala",
          "Sabzi Masala",
          "Sambar Masala",
          "Sindhi Biryani Masala",
          "Roghan Gosh Masala",
          "Tandoori Masala",
          "All Dish Masala",
          "Bengali Fish Masala",
          "Kashmiri + Guntur Chilli",
        ],
      },
    ],
  },
  {
    id: "special-seasonings",
    label: "Special Seasonings",
    image: "/products-page/spices/special-seasonings.webp",
    imagePosition: "left",
    groups: [
      {
        title: null,
        items: [
          "Rosemary",
          "Thyme",
          "Basil",
          "Oregano",
          "Sage",
          "Bay Leaves",
          "Paprika",
          "Sumac",
          "Asafoetida",
          "Fennel Seeds",
          "Poppy Seeds (Khus Khus)",
          "Sesame Seeds",
          "Mustard Seeds",
          "Pink Peppercorns",
          "Himalayan Pink Salt",
          "Black Salt",
        ],
      },
    ],
  },
];