export const INSTANT_FOOD_SECTIONS = [
  {
    id: "retort",
    label: "Retort",
    image: "/products-page/instant-foods/retort.webp",
    imagePosition: "right",
    groups: [
      {
        title: "Rice",
        items: [
          "Basmati Rice",
          "Brown Basmati Rice",
          "Turmeric Basmati Rice",
          "Chinese Fried Rice",
          "Lemon Rice",
          "Vegetable Biryani",
          "Vegetable Pulao Rice",
          "Mexican Rice",
          "Long Grain Rice",
          "Cilantro & Lime Rice",
          "Coconut Rice",
        ],
      },
      {
        title: "Curries",
        items: [
          "Malai Kofta Curry",
          "Rajma Masala",
          "Dal Makhani",
          "Yellow Dal Tadka",
          "Punjabi Chole",
          "Kadhi Pakoda",
          "Dal Palak",
          "Pav Bhaji",
          "Aloo Methi",
          "Aloo Palak",
          "Baigan Bharta",
        ],
      },
      {
        title: "Combos",
        items: [
          "Chickpeas Curry + Basmati Rice",
          "Black Gram Lentil Curry + Basmati Rice",
          "Red Kidney Bean Curry + Basmati Rice",
        ],
      },
    ],
  },
  {
    id: "noodles-pasta",
    label: "Noodles & Pasta",
    image: "/products-page/instant-foods/noodles-pasta.webp",
    imagePosition: "left",
    groups: [
      {
        title: "Noodles/Pasta",
        items: [
          "Ragi (Finger Millet) Noodles/Pasta",
          "Whole-Wheat Pasta/Noodles",
          "Soba Noodles (Buckwheat)",
          "Brown Rice Pasta/Noodles",
          "Chickpea Pasta",
          "Lentil Pasta (Red or Green)",
          "Black Bean Noodles",
        ],
      },
      {
        title: "Gourmet & Healthy",
        items: [
          "Red Lentil Pasta",
          "Chickpea Pasta",
          "Red Lentil Spaghetti",
          "Green Dal & Edamame Spaghetti",
          "Moong & Edamame Spaghetti",
          "Chickpea & Soyabean Spaghetti",
          "Chickpea & Soyabean Fettuccine",
          "Red Lentil Fettuccine",
          "Chickpea Lasagne",
          "Red Lentil Crisps (Sea Salt, Garlic & Herbs Truffle)",
          "Red Lentil Rice",
          "Sattu Rice",
          "Edamame Rice",
          "Tricolor Quinoa",
          "White Quinoa",
          "Quinoa Crispers",
        ],
      },
    ],
  },
];