export const BEVERAGE_SECTIONS = [
  {
    id: "alphanso-mango",
    label: "Alphanso Mango",
    image: "/products/beverages/mango.webp",
    imagePosition: "right",
    groups: [
      {
        title: "Product Highlights",
        items: [
          "High-protein smoothie made with real Alphanso mango",
          "10g Protein",
          "5g Fibre",
          "119 kcal",
          "Supports muscle recovery",
          "Sustained energy",
          "Calcium and protein in every glass",
          "Ready in under 30 seconds",
        ],
      },
      {
        title: "Ingredients & Benefits",
        items: [
          "Ratnagiri Alphanso Mango Pulp",
          "Banana Pulp",
          "Milk Protein Concentrate",
          "Cashew & Almonds",
          "Chia Seeds",
        ],
      },
    ],
  },
  {
    id: "strawberry",
    label: "Strawberry",
    image: "/products/beverages/strawberry.webp",
    imagePosition: "left",
    groups: [
      {
        title: "Product Highlights",
        items: [
          "High-protein smoothie made with real fruit",
          "9g Protein",
          "5g Fibre",
          "117 kcal",
          "Protein-rich for muscle recovery",
          "Sustained energy",
          "Calcium and protein in every glass",
          "Ready in under 30 seconds",
        ],
      },
      {
        title: "Ingredients & Benefits",
        items: [
          "Strawberry Pulp with Seed",
          "Fresh Beetroot Pulp",
          "Milk Protein Concentrate",
          "Chia Seeds",
          "Almonds & Cashew",
        ],
      },
    ],
  },
  {
    id: "apple-cinnamon",
    label: "Apple Cinnamon",
    image: "/products/beverages/apple-cinnamon.webp",
    imagePosition: "right",
    groups: [
      {
        title: "Product Highlights",
        items: [
          "High-protein smoothie, naturally spiced",
          "10g Protein",
          "5.2g Fibre",
          "146 kcal",
          "Supports muscle recovery",
          "Fibre-rich for smooth digestion",
          "Sustained energy",
          "Naturally sweetened with no added sugar",
        ],
      },
      {
        title: "Ingredients & Benefits",
        items: [
          "Apple Pulp",
          "Cinnamon",
          "Milk Protein Concentrate",
          "Oats",
          "Chia Seeds",
          "Sun Fibre",
          "Almonds",
          "Cashew",
          "Pumpkin Seeds",
          "Rosemary Extract",
          "Monk Fruit Extract",
        ],
      },
    ],
  },
  {
    id: "banana-choco",
    label: "Banana Choco",
    image: "/products/beverages/banana-choco.webp",
    imagePosition: "left",
    groups: [
      {
        title: "Product Highlights",
        items: [
          "High-protein smoothie with rich chocolate flavour",
          "10g Protein",
          "5.6g Fibre",
          "139 kcal",
          "Supports muscle recovery",
          "Fibre-rich for smooth digestion",
          "Sustained energy",
          "Rich in antioxidants",
        ],
      },
      {
        title: "Ingredients & Benefits",
        items: [
          "Banana Pulp",
          "Cocoa Powder",
          "Milk Protein Concentrate",
          "Oats",
          "Chia Seeds",
          "Sun Fibre",
          "Almonds",
          "Skim Milk Powder",
          "Rosemary Extract",
          "Monk Fruit Extract",
        ],
      },
    ],
  },
  {
    id: "chickoo",
    label: "Chickoo",
    image: "/products/beverages/chickoo.webp",
    imagePosition: "right",
    groups: [
      {
        title: "Product Highlights",
        items: [
          "High-protein smoothie with natural sapodilla sweetness",
          "10g Protein",
          "8g Fibre",
          "145 kcal",
          "Supports muscle recovery",
          "Extra fibre-rich for digestive comfort",
          "Sustained energy",
          "Calcium and protein in every glass",
        ],
      },
      {
        title: "Ingredients & Benefits",
        items: [
          "Chickoo (Sapodilla) Pulp",
          "Milk Protein Concentrate",
          "Oats",
          "Almonds",
          "Chia Seeds",
          "Sun Fibre",
          "Skim Milk Powder",
          "Rosemary Extract",
          "Monk Fruit Extract",
        ],
      },
    ],
  },
];